CREATE TABLE theme (
    theme_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    theme_name VARCHAR(100) NOT NULL
);

CREATE TABLE types (
    types_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    types_name VARCHAR(100) NOT NULL
);

CREATE TABLE article (
    article_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author VARCHAR(100) NOT NULL,
    title TEXT NOT NULL,
    arttext TEXT NOT NULL,
    arturl TEXT NOT NULL,
    mark INT NULL,
    parsedate VARCHAR(100) NOT NULL,
    createdate VARCHAR(100) NOT NULL,
    types_id INT REFERENCES types(types_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE article_theme (
    article_id INT REFERENCES article(article_id) ON DELETE CASCADE,
    theme_id   INT REFERENCES theme(theme_id) ON DELETE CASCADE,
    PRIMARY KEY (article_id, theme_id)
);

CREATE TABLE chunk (
    chunk_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chunk_text TEXT NOT NULL,
    payload json NOT NULL,
    article_id INT REFERENCES article(article_id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_article_types_id ON article(types_id);
CREATE INDEX idx_chunk_article_id ON chunk(article_id);
CREATE INDEX idx_arttheme_article_id ON article_theme(article_id);
CREATE INDEX idx_arttheme_theme_id ON article_theme(theme_id);